In [155]:
# Importing modules  for Cleaning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [156]:
#Loading Pandas Data Frame
df = pd.read_csv(r'/content/sample_data/VrindaStoreDatanalysis1 (1).csv')

In [157]:
#Printing The firet 10 Rows of Data
df.head(10)

,index,Order ID,Cust ID,Gender,Age,Age Group,Date,Month,Status,Channel,...,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,\/,B2B
0,1,171-1029312-3038738,1029312,Women,44,Adults,12/4/2022,Dec,Delivered,Myntra,...,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,NaN
1,2,405-2183842-2225946,2183842,Women,29,Teenager,12/4/2022,Dec,Delivered,Ajio,...,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,NaN
2,3,171-1641533-8921966,1641533,Women,67,Senior,12/4/2022,Dec,Delivered,Myntra,...,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,NaN
3,4,404-7490807-6300351,7490807,Women,20,Teenager,12/4/2022,Dec,Delivered,Amazon,...,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,NaN
4,5,403-9293516-4577154,9293516,Women,62,Senior,12/4/2022,Dec,Delivered,Myntra,...,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,NaN
5,6,407-1298130-0368305,1298130,Men,49,Adults,12/4/2022,Dec,Delivered,Flipkart,...,Western Dress,XXL,1,INR,735,SANGLI MIRAJ KUPWAD,MAHARASHTRA,416436,IN,NaN
6,7,407-1298130-0368305,1298130,Women,23,Teenager,12/4/2022,Dec,Delivered,Meesho,...,kurta,XXL,1,INR,735,BENGALURU,KARNATAKA,560029,IN,NaN
7,8,171-5561216-3398711,5561216,Women,70,Senior,12/4/2022,Dec,Delivered,Others,...,kurta,M,1,INR,435,GURUGRAM,HARYANA,122001,IN,NaN
8,9,408-2935263-2935550,2935263,Women,75,Senior,12/4/2022,Dec,Delivered,Amazon,...,kurta,XL,1,INR,385,BENGALURU,KARNATAKA,562149,IN,NaN
9,10,404-2648970-9042715,2648970,Women,43,Adults,12/4/2022,Dec,Delivered,Myntra,...,kurta,L,1,INR,771,VIJAYAWADA,ANDHRA PRADESH,520002,IN,NaN

In [158]:
#Printing information about Data Frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31047 entries, 0 to 31046
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             31047 non-null  int64
 1   Order ID          31047 non-null  object
 2   Cust ID           31047 non-null  int64
 3   Gender            31047 non-null  object
 4   Age               31047 non-null  int64
 5   Age Group         31047 non-null  object
 6   Date              31047 non-null  object
 7   Month             31047 non-null  object
 8   Status            31047 non-null  object
 9   Channel           31047 non-null  object
 10  SKU               31047 non-null  object
 11  Category          31047 non-null  object
 12  Size              31047 non-null  object
 13  Qty               31047 non-null  int64
 14  currency          31047 non-null  object
 15  Amount            31047 non-null  int64
 16  ship-city         31047 non-null  object
 17  ship-state        31047 non-null  object
 18  ship-postal-code  31047 non-null  int64
 19  \/                31047 non-null  object
 20  B2B               186 non-null    float64
dtypes: float64(1), int64(6), object(14)
memory usage: 5.0+ MB

In [159]:
#Removing unwanted Columns from Data frame
df.drop(columns=["Month","Status","currency","\/",'B2B',"SKU",'ship-city'],inplace = True)
df.head(10)

,index,Order ID,Cust ID,Gender,Age,Age Group,Date,Channel,Category,Size,Qty,Amount,ship-state,ship-postal-code
0,1,171-1029312-3038738,1029312,Women,44,Adults,12/4/2022,Myntra,kurta,XXL,1,376,PUNJAB,140301
1,2,405-2183842-2225946,2183842,Women,29,Teenager,12/4/2022,Ajio,Set,L,1,1449,HARYANA,122002
2,3,171-1641533-8921966,1641533,Women,67,Senior,12/4/2022,Myntra,Set,S,1,453,WEST BENGAL,700029
3,4,404-7490807-6300351,7490807,Women,20,Teenager,12/4/2022,Amazon,Set,M,1,729,TAMIL NADU,613007
4,5,403-9293516-4577154,9293516,Women,62,Senior,12/4/2022,Myntra,kurta,XXL,1,544,HARYANA,122001
5,6,407-1298130-0368305,1298130,Men,49,Adults,12/4/2022,Flipkart,Western Dress,XXL,1,735,MAHARASHTRA,416436
6,7,407-1298130-0368305,1298130,Women,23,Teenager,12/4/2022,Meesho,kurta,XXL,1,735,KARNATAKA,560029
7,8,171-5561216-3398711,5561216,Women,70,Senior,12/4/2022,Others,kurta,M,1,435,HARYANA,122001
8,9,408-2935263-2935550,2935263,Women,75,Senior,12/4/2022,Amazon,kurta,XL,1,385,KARNATAKA,562149
9,10,404-2648970-9042715,2648970,Women,43,Adults,12/4/2022,Myntra,kurta,L,1,771,ANDHRA PRADESH,520002

In [160]:
# Changing the data type of Date from String to Date Format
df['Date'] = pd.to_datetime(df['Date'])
df.head(10)

,index,Order ID,Cust ID,Gender,Age,Age Group,Date,Channel,Category,Size,Qty,Amount,ship-state,ship-postal-code
0,1,171-1029312-3038738,1029312,Women,44,Adults,2022-12-04,Myntra,kurta,XXL,1,376,PUNJAB,140301
1,2,405-2183842-2225946,2183842,Women,29,Teenager,2022-12-04,Ajio,Set,L,1,1449,HARYANA,122002
2,3,171-1641533-8921966,1641533,Women,67,Senior,2022-12-04,Myntra,Set,S,1,453,WEST BENGAL,700029
3,4,404-7490807-6300351,7490807,Women,20,Teenager,2022-12-04,Amazon,Set,M,1,729,TAMIL NADU,613007
4,5,403-9293516-4577154,9293516,Women,62,Senior,2022-12-04,Myntra,kurta,XXL,1,544,HARYANA,122001
5,6,407-1298130-0368305,1298130,Men,49,Adults,2022-12-04,Flipkart,Western Dress,XXL,1,735,MAHARASHTRA,416436
6,7,407-1298130-0368305,1298130,Women,23,Teenager,2022-12-04,Meesho,kurta,XXL,1,735,KARNATAKA,560029
7,8,171-5561216-3398711,5561216,Women,70,Senior,2022-12-04,Others,kurta,M,1,435,HARYANA,122001
8,9,408-2935263-2935550,2935263,Women,75,Senior,2022-12-04,Amazon,kurta,XL,1,385,KARNATAKA,562149
9,10,404-2648970-9042715,2648970,Women,43,Adults,2022-12-04,Myntra,kurta,L,1,771,ANDHRA PRADESH,520002

In [161]:
# Updating  Gender Column as "M" for Male and "W" for Women
df["Gender"] = df["Gender"].apply(lambda x : 'M' if x == "Male" else "W")
df.head(10)

,index,Order ID,Cust ID,Gender,Age,Age Group,Date,Channel,Category,Size,Qty,Amount,ship-state,ship-postal-code
0,1,171-1029312-3038738,1029312,W,44,Adults,2022-12-04,Myntra,kurta,XXL,1,376,PUNJAB,140301
1,2,405-2183842-2225946,2183842,W,29,Teenager,2022-12-04,Ajio,Set,L,1,1449,HARYANA,122002
2,3,171-1641533-8921966,1641533,W,67,Senior,2022-12-04,Myntra,Set,S,1,453,WEST BENGAL,700029
3,4,404-7490807-6300351,7490807,W,20,Teenager,2022-12-04,Amazon,Set,M,1,729,TAMIL NADU,613007
4,5,403-9293516-4577154,9293516,W,62,Senior,2022-12-04,Myntra,kurta,XXL,1,544,HARYANA,122001
5,6,407-1298130-0368305,1298130,W,49,Adults,2022-12-04,Flipkart,Western Dress,XXL,1,735,MAHARASHTRA,416436
6,7,407-1298130-0368305,1298130,W,23,Teenager,2022-12-04,Meesho,kurta,XXL,1,735,KARNATAKA,560029
7,8,171-5561216-3398711,5561216,W,70,Senior,2022-12-04,Others,kurta,M,1,435,HARYANA,122001
8,9,408-2935263-2935550,2935263,W,75,Senior,2022-12-04,Amazon,kurta,XL,1,385,KARNATAKA,562149
9,10,404-2648970-9042715,2648970,W,43,Adults,2022-12-04,Myntra,kurta,L,1,771,ANDHRA PRADESH,520002

In [162]:
df.dropna()

,index,Order ID,Cust ID,Gender,Age,Age Group,Date,Channel,Category,Size,Qty,Amount,ship-state,ship-postal-code
0,1,171-1029312-3038738,1029312,W,44,Adults,2022-12-04,Myntra,kurta,XXL,1,376,PUNJAB,140301
1,2,405-2183842-2225946,2183842,W,29,Teenager,2022-12-04,Ajio,Set,L,1,1449,HARYANA,122002
2,3,171-1641533-8921966,1641533,W,67,Senior,2022-12-04,Myntra,Set,S,1,453,WEST BENGAL,700029
3,4,404-7490807-6300351,7490807,W,20,Teenager,2022-12-04,Amazon,Set,M,1,729,TAMIL NADU,613007
4,5,403-9293516-4577154,9293516,W,62,Senior,2022-12-04,Myntra,kurta,XXL,1,544,HARYANA,122001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31042,31043,405-4724097-1016369,4724097,W,60,Senior,2022-01-06,Flipkart,kurta,XL,1,565,MAHARASHTRA,412307
31043,31044,405-4724097-1016369,4724097,W,34,Adults,2022-01-06,Myntra,Set,S,1,939,KARNATAKA,560061
31044,31045,408-3572295-5992330,3572295,W,29,Teenager,2022-01-06,Amazon,Set,L,1,1115,UTTARAKHAND,262501
31045,31046,405-1423498-9705162,1423498,W,46,Adults,2022-01-06,Amazon,kurta,M,1,399,MAHARASHTRA,424006
31046,31047,408-4694875-8249153,4694875,W,36,Adults,2022-01-06,Flipkart,Western Dress,3XL,1,791,TELANGANA,506001

In [163]:
df.describe()

,index,Cust ID,Age,Date,Qty,Amount,ship-postal-code
count,31047.00000,3.104700e+04,31047.000000,31047,31047.000000,31047.000000,31047.000000
mean,15524.00000,4.936824e+06,39.496570,2022-06-15 06:41:39.719779584,1.006120,682.074822,460474.587206
min,1.00000,8.950000e+02,18.000000,2022-01-04 00:00:00,1.000000,229.000000,110001.000000
25%,7762.50000,2.416471e+06,28.000000,2022-03-06 00:00:00,1.000000,486.000000,313001.000000
50%,15524.00000,4.909885e+06,37.000000,2022-06-06 00:00:00,1.000000,646.000000,500028.000000
75%,23285.50000,7.454182e+06,47.000000,2022-09-06 00:00:00,1.000000,794.000000,600040.000000
max,31047.00000,9.999233e+06,78.000000,2022-12-06 00:00:00,5.000000,3036.000000,855117.000000
std,8962.64124,2.900678e+06,15.117233,NaN,0.094088,268.582173,198116.733009

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31047 entries, 0 to 31046
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             31047 non-null  int64
 1   Order ID          31047 non-null  object
 2   Cust ID           31047 non-null  int64
 3   Gender            31047 non-null  object
 4   Age               31047 non-null  int64
 5   Age Group         31047 non-null  object
 6   Date              31047 non-null  datetime64[ns]
 7   Channel           31047 non-null  object
 8   Category          31047 non-null  object
 9   Size              31047 non-null  object
 10  Qty               31047 non-null  int64
 11  Amount            31047 non-null  int64
 12  ship-state        31047 non-null  object
 13  ship-postal-code  31047 non-null  int64
dtypes: datetime64[ns](1), int64(6), object(7)
memory usage: 3.3+ MB

In [170]:
#Removing Spaces and renaming columns
df.rename(columns={'Order ID':'Order_ID','Cust ID':'Cust_ID','Age Group':'Age_Group','Channel  ':"E-com_Platform"},inplace=True)

In [171]:
#Get the customer details of Myntra order from Women only and cost  below 1000Rs
df[(df["E-com_Platform"] =='Myntra')&(df["Gender"] == "W")&(df["Amount"]<1000) ]

,index,Order_ID,Cust_ID,Gender,Age,Age_Group,Date,E-com_Platform,Category,Size,Qty,Amount,ship-state,ship-postal-code
0,1,171-1029312-3038738,1029312,W,44,Adults,2022-12-04,Myntra,kurta,XXL,1,376,PUNJAB,140301
2,3,171-1641533-8921966,1641533,W,67,Senior,2022-12-04,Myntra,Set,S,1,453,WEST BENGAL,700029
4,5,403-9293516-4577154,9293516,W,62,Senior,2022-12-04,Myntra,kurta,XXL,1,544,HARYANA,122001
9,10,404-2648970-9042715,2648970,W,43,Adults,2022-12-04,Myntra,kurta,L,1,771,ANDHRA PRADESH,520002
11,12,404-2648970-9042715,2648970,W,45,Adults,2022-12-04,Myntra,Top,M,1,399,TAMIL NADU,631003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31033,31034,403-0741097-5754745,741097,W,30,Adults,2022-01-06,Myntra,kurta,L,1,280,TAMIL NADU,641041
31034,31035,408-6099698-0085151,6099698,W,39,Adults,2022-01-06,Myntra,Western Dress,L,1,721,KERALA,695561
31037,31038,405-6870909-7366760,6870909,W,73,Senior,2022-01-06,Myntra,Western Dress,XL,1,735,UTTAR PRADESH,208001
31039,31040,405-7447678-6283558,7447678,W,30,Adults,2022-01-06,Myntra,Top,S,1,385,TELANGANA,500015
31043,31044,405-4724097-1016369,4724097,W,34,Adults,2022-01-06,Myntra,Set,S,1,939,KARNATAKA,560061